export default [
  {
    image: 'limit-orders.jpeg',
    text: 'TYMIO Innovates DeFi Landscape With Limit Orders and Fixed Yield',
    author: 'Bitcoin.com',
    date: '26.04.2024',
    link: 'https://news.bitcoin.com/tymio-innovates-defi-landscape-with-limit-orders-and-fixed-yield/',
    imgAthor: 'btc.com-logo.jpg',
  },
  {
    image: 'fourth-image-tymio.png',
    text: 'TYMIO’s Role in DeFi: Founder Georgii Verbitskii Shares His Vision',
    author: 'blockchainreporter.net',
    date: '26.04.2024',
    link: 'https://blockchainreporter.net/tymios-role-in-defi-founder-georgii-verbitskii-shares-his-vision/',
    imgAthor: 'blockchain-repoter-logo.png',
  },
  {
    image: 'crypto-news.webp',
    text: 'TYMIO Unveils New Smart Contract Upgrades and Platform Enhancements',
    author: 'crypto.news',
    date: '26.04.2024',
    link: 'https://crypto.news/tymio-unveils-new-smart-contract-upgrades-and-platform-enhancements/',
    imgAthor: 'cryptonews-logo.png',
  },
  {
    image: 'mobile-tymio-logo.png',
    text: 'How to Earn in a Sideways Market with TYMIO?',
    author: 'coinmarketcap.com',
    date: '26.04.2024',
    link: 'https://coinmarketcap.com/community/articles/662f74d69a408f3e17a5a1d0/',
    imgAthor: 'coinmarketcap-logo.png',
  },

  {
    image: 'limit-orders.jpeg',
    text: '1TYMIO Innovates DeFi Landscape With Limit Orders and Fixed Yield',
    author: 'Bitcoin.com',
    date: '26.04.2024',
    link: 'https://news.bitcoin.com/tymio-innovates-defi-landscape-with-limit-orders-and-fixed-yield/',
    imgAthor: 'btc.com-logo.jpg',
  },
  {
    image: 'fourth-image-tymio.png',
    text: '2TYMIO’s Role in DeFi: Founder Georgii Verbitskii Shares His Vision',
    author: 'blockchainreporter.net',
    date: '26.04.2024',
    link: 'https://blockchainreporter.net/tymios-role-in-defi-founder-georgii-verbitskii-shares-his-vision/',
    imgAthor: 'blockchain-repoter-logo.png',
  },
  {
    image: 'crypto-news.webp',
    text: '3TYMIO Unveils New Smart Contract Upgrades and Platform Enhancements',
    author: 'crypto.news',
    date: '26.04.2024',
    link: 'https://crypto.news/tymio-unveils-new-smart-contract-upgrades-and-platform-enhancements/',
    imgAthor: 'cryptonews-logo.png',
  },
  {
    image: 'mobile-tymio-logo.png',
    text: '4How to Earn in a Sideways Market with TYMIO?',
    author: 'coinmarketcap.com',
    date: '26.04.2024',
    link: 'https://coinmarketcap.com/community/articles/662f74d69a408f3e17a5a1d0/',
    imgAthor: 'coinmarketcap-logo.png',
  },
  {
    image: 'mobile-tymio-logo.png',
    text: '5How to Earn in a Sideways Market with TYMIO?',
    author: 'coinmarketcap.com',
    date: '26.04.2024',
    link: 'https://coinmarketcap.com/community/articles/662f74d69a408f3e17a5a1d0/',
    imgAthor: 'coinmarketcap-logo.png',
  },
  {
    image: 'mobile-tymio-logo.png',
    text: '6How to Earn in a Sideways Market with TYMIO?',
    author: 'coinmarketcap.com',
    date: '26.04.2024',
    link: 'https://coinmarketcap.com/community/articles/662f74d69a408f3e17a5a1d0/',
    imgAthor: 'coinmarketcap-logo.png',
  },
];
